name: SonikFM API Staging Client Deployment

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Transfer to EC2 via SSH_PRIVATE_KEY
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
          REMOTE_HOST: ${{secrets.HOST_DNS}}
          REMOTE_USER: ${{secrets.USERNAME}}
          TARGET: ${{secrets.STAGING_TARGET_DIR}}

      - name: Build & Execute
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} << 'EOF'
            cd ${{ secrets.STAGING_TARGET_DIR }}
            npm install
            npm run build
            rm -rf ./../${{ secrets.STAGING_APP_NAME }}/dist
            mv ./dist ./../${{ secrets.STAGING_APP_NAME }}/
            # pm2 restart 0 --update-env
          EOF
          rm private_key.pem
