name: SonikFM API Staging Client Deployment

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Transfer to EC2 via SSH_PRIVATE_KEY
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
          REMOTE_HOST: ${{secrets.HOST_DNS}}
          REMOTE_USER: ${{secrets.USERNAME}}
          TARGET: ${{secrets.STAGING_TARGET_DIR}}
